paginacao:
  qtd_por_pagina: 25
#spring:
#  profiles:
#    active: test
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/flyway
    username: root
    password: Dfreitas2466